[workspace]
members = [
    "exonum",
    "services/configuration",
    "services/time",
    "services/cryptocurrency",
    "components/build",
    "components/crypto",
    "components/derive",
]
exclude = [ "exonum/fuzz" ]
